# Generated by Django 2.0 on 2018-02-11 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180208_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='height',
        ),
        migrations.RemoveField(
            model_name='post',
            name='width',
        ),
    ]
